var url_comparador='../ajax/add-comparador.php';
var cardStructure = '<div class="col-md-4 col-sm-6 col-xs-12 general-box" style="background-image: url(\'{BCKGRND_IMG}\')">';
cardStructure += ' <a href="{HREF}" data-titulo=​"Mosaico:{PROMO_TYPE}" data-categoria=​"{ETIQUETA}" data-canal=​"mitelcelweb" data-evento=​"clicMosaico">';
cardStructure += ' <div class="contenedor-mosaico-empresas" id="conferencia-web" aria-label="{ARIAL_LABEL}">';
cardStructure += '  <div class="promo-box"></div>';
cardStructure += '  <div class="promo-box--contenido promo-box--empresas">';
cardStructure += '   <div class="promo-box--contenido-interno">';
cardStructure += '    <div class="row date-box">';
cardStructure += '     <img src="scrAssets/icon-calendar.png" alt="">';
cardStructure += '     <div class="content-date">';
cardStructure += '      <p class="date">Vigencia</p>';
cardStructure += '      <p class="date">{FECHA_VIG}</p>';
cardStructure += '     </div>';
cardStructure += '    </div>';
cardStructure += '    <p class="title">{PROMO_TITLE}</p>';
cardStructure += '    <div class="descripcion">';
cardStructure += '     <p class="">{DESCRIPTION}</p>';
cardStructure += '    </div>';
cardStructure += '    <div class="btn-box">';
cardStructure += '     <button class="telcel-controles-cta--borde" type="button" name="button">Ver más</button>';
cardStructure += '    </div>';
cardStructure += '   </div>';
cardStructure += '  </div>';
cardStructure += ' </div>';
cardStructure += ' </a>';
cardStructure += '</div>';

var cardStructureSM = '<div class="column">';
cardStructureSM += ' <a href="{HREF}">';
cardStructureSM += '<div class="card" style="background-image: url(\'{BCKGRND_IMG}\')">';
cardStructureSM += '  <h3>{FECHA_VIG}</h3>';
cardStructureSM += '  <p>{PROMO_TITLE}</p>';
cardStructureSM += '  <p>{DESCRIPTION}</p>';
cardStructureSM += '</div>';
cardStructureSM += ' </a>';
cardStructureSM += '</div>';

var cardStructureSMtd = '<td><div class="column">';
cardStructureSMtd += ' <a href="{HREF}">';
cardStructureSMtd += '<div class="card" style="background-image: url(\'{BCKGRND_IMG}\')">';
cardStructureSMtd += '  <br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />';
cardStructureSMtd += '  <p>{PROMO_TITLE}</p>';
cardStructureSMtd += '  <p>{DESCRIPTION}</p>';
cardStructureSMtd += '  <div class="label">&nbsp;{LABEL}</div>';
cardStructureSMtd += '  <div class="date-box">';
cardStructureSMtd += '   <img src="srcAssets/icon-calendar.png" alt="">';
cardStructureSMtd += '   <div class="content-date">';
cardStructureSMtd += '    <p class="date">Vigencia</p>';
cardStructureSMtd += '    <p class="date">{FECHA_INI} al {FECHA_FIN}</p>';
cardStructureSMtd += '   </div>';
cardStructureSMtd += '  </div>';
cardStructureSMtd += '</div>';
cardStructureSMtd += ' </a>';
cardStructureSMtd += '</div></td>';

