-- MySQL Script generated by MySQL Workbench
-- Wed Sep 25 17:03:56 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bds_consola_universal
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bds_consola_universal` ;

-- -----------------------------------------------------
-- Schema bds_consola_universal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bds_consola_universal` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `bds_consola_universal` ;

-- -----------------------------------------------------
-- Table `bds_consola_universal`.`cfConfigurations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bds_consola_universal`.`cfConfigurations` ;

CREATE TABLE IF NOT EXISTS `bds_consola_universal`.`cfConfigurations` (
  `IdConfiguration` INT(11) NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(25) NULL DEFAULT NULL,
  `ValueOf` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`IdConfiguration`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;

INSERT INTO `bds_consola_universal`.`cfConfigurations` (`Description`, `ValueOf`) VALUES ('CompanyEncryptCode', '~KöAtcHy¬');
INSERT INTO `bds_consola_universal`.`cfConfigurations` (`Description`, `ValueOf`) VALUES ('CompanyName', 'Köatchy');
INSERT INTO `bds_consola_universal`.`cfConfigurations` (`Description`, `ValueOf`) VALUES ('EmailHost', 'smtp.gmail.com');
INSERT INTO `bds_consola_universal`.`cfConfigurations` (`Description`, `ValueOf`) VALUES ('EmailPort', '587');
INSERT INTO `bds_consola_universal`.`cfConfigurations` (`Description`, `ValueOf`) VALUES ('EmailFromAccout', 'abarrios7007@gmail.com');
INSERT INTO `bds_consola_universal`.`cfConfigurations` (`Description`, `ValueOf`) VALUES ('AutorizationRequest', 'wDo3rXrE/');
INSERT INTO `bds_consola_universal`.`cfConfigurations` (`Description`, `ValueOf`) VALUES ('PhotoDirectory', 'C:\\src\\configGenerator\\src\\main\\webapp\\assets\\photos');


-- -----------------------------------------------------
-- Table `bds_consola_universal`.`ctCountries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bds_consola_universal`.`ctCountries` ;

CREATE TABLE IF NOT EXISTS `bds_consola_universal`.`ctCountries` (
  `IdCountry` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(50) NOT NULL,
  `Shortname` VARCHAR(5) NOT NULL,
  `Capital` VARCHAR(50) NOT NULL,
  `Currency` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`IdCountry`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

INSERT INTO `bds_consola_universal`.`ctCountries` (`Name`, `Shortname`, `Capital`, `Currency`) VALUES ('México', 'MX', 'CDMX', '$');

-- -----------------------------------------------------
-- Table `bds_consola_universal`.`ctOrganizationRoles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bds_consola_universal`.`ctOrganizationRoles` ;

CREATE TABLE IF NOT EXISTS `bds_consola_universal`.`ctOrganizationRoles` (
  `IdOrganizationRol` INT(11) NOT NULL AUTO_INCREMENT,
  `NameES` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`IdOrganizationRol`)
  )
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

INSERT INTO `bds_consola_universal`.`ctOrganizationRoles` (`namees`) VALUES ('Director');
INSERT INTO `bds_consola_universal`.`ctOrganizationRoles` (`namees`) VALUES ('Gerente');
INSERT INTO `bds_consola_universal`.`ctOrganizationRoles` (`namees`) VALUES ('Ejecutivo de ventas');
INSERT INTO `bds_consola_universal`.`ctOrganizationRoles` (`namees`) VALUES ('Ejecutivo de compras');
INSERT INTO `bds_consola_universal`.`ctOrganizationRoles` (`namees`) VALUES ('Contador');
INSERT INTO `bds_consola_universal`.`ctOrganizationRoles` (`namees`) VALUES ('Ingeniero');
INSERT INTO `bds_consola_universal`.`ctOrganizationRoles` (`namees`) VALUES ('Desarrollador de software');
INSERT INTO `bds_consola_universal`.`ctOrganizationRoles` (`namees`) VALUES ('Arquitecto');

-- -----------------------------------------------------
-- Table `bds_consola_universal`.`ctUserAreas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bds_consola_universal`.`ctUserAreas` ;

CREATE TABLE IF NOT EXISTS `bds_consola_universal`.`ctUserAreas` (
  `IdUserArea` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(50) NOT NULL,
  `Notify` CHAR(1) NOT NULL,
  PRIMARY KEY (`IdUserArea`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

INSERT INTO `bds_consola_universal`.`ctUserAreas` (`name`, `Notify`) VALUES ('Infraestructura', 'Y');
INSERT INTO `bds_consola_universal`.`ctUserAreas` (`name`, `Notify`) VALUES ('Negocio', 'Y');
INSERT INTO `bds_consola_universal`.`ctUserAreas` (`name`, `Notify`) VALUES ('Desarrollo BE', 'Y');
INSERT INTO `bds_consola_universal`.`ctUserAreas` (`name`, `Notify`) VALUES ('Desarrollo Apps', 'Y');
INSERT INTO `bds_consola_universal`.`ctUserAreas` (`name`, `Notify`) VALUES ('QA', 'Y');
INSERT INTO `bds_consola_universal`.`ctUserAreas` (`name`, `Notify`) VALUES ('Soporte', 'Y');
INSERT INTO `bds_consola_universal`.`ctUserAreas` (`name`, `Notify`) VALUES ('Proyectos', 'Y');

-- -----------------------------------------------------
-- Table `bds_consola_universal`.`ctUsers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bds_consola_universal`.`ctUsers` ;

CREATE TABLE IF NOT EXISTS `bds_consola_universal`.`ctUsers` (
  `IdUser` INT(11) NOT NULL AUTO_INCREMENT,
  `IdUserArea` INT(11) NULL,
  `IdOrganization` INT(11) NULL,
  `IdOrganizationRol` INT(11) NULL,
  `Password` VARCHAR(250) NOT NULL,
  `Name` VARCHAR(50) NOT NULL,
  `Lastname` VARCHAR(50) NULL,
  `Email` VARCHAR(150) NOT NULL,
  `Superuser` CHAR(1) NOT NULL,
  `Confirmed` CHAR(1) NOT NULL,
  `Photo` VARCHAR(100) NULL,
  `Unavaibled` CHAR(1) NOT NULL,
  `Created_Datetime` DATETIME NOT NULL,
  `Created_Platform` VARCHAR(10) NOT NULL,
  `Updated_Datetime` DATETIME NULL,
  `Updated_Platform` VARCHAR(10) NULL,
  PRIMARY KEY (`IdUser`),
  CONSTRAINT `FK_User_Area`
    FOREIGN KEY (`IdUserArea`)
    REFERENCES `bds_consola_universal`.`ctUserAreas` (`IdUserArea`),
  CONSTRAINT `FK_User_Rol`
    FOREIGN KEY (`IdOrganizationRol`)
    REFERENCES `bds_consola_universal`.`ctOrganizationRoles` (`IdOrganizationRol`)
    )
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

INSERT INTO `bds_consola_universal`.`ctUsers` (`IdUserArea`, `Password`, `Unavaibled`, `Name`, `lastname`, `Email`, `Superuser`, `Confirmed`, `IdOrganization`, `IdOrganizationRol`, `Created_Platform`, `Created_Datetime`) VALUES (1, 'admin', 'N', 'Alfredo', 'Barrios', 'alfredo.barrios@speedymovil.com', 'Y', 'Y', 2, 1, 'INIT_ROW', SYSDATE());


-- -----------------------------------------------------
-- Table `bds_consola_universal`.`ctOrganizations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bds_consola_universal`.`ctOrganizations` ;

CREATE TABLE IF NOT EXISTS `bds_consola_universal`.`ctOrganizations` (
  `IdOrganization` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(250) NOT NULL,
  `IconUrl` VARCHAR(250) NULL,
  `BadgeUrl` VARCHAR(250) NULL,
  `IdUserOnCharge` INT(11) NULL,
  `Created_Datetime` DATETIME NOT NULL,
  `Created_Platform` VARCHAR(10) NOT NULL,
  `Updated_Datetime` DATETIME NULL,
  `Updated_Platform` VARCHAR(10) NULL,
  PRIMARY KEY (`IdOrganization`)
  )
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

INSERT INTO `bds_consola_universal`.`ctOrganizations` (`Name`, `IdUserOnCharge`, `Created_Platform`, `Created_Datetime`) VALUES ('Ninguna', 1, 'INIT_ROW', SYSDATE());
INSERT INTO `bds_consola_universal`.`ctOrganizations` (`Name`, `IdUserOnCharge`, `Created_Platform`, `Created_Datetime`) VALUES ('Köatchy', 1, 'INIT_ROW', SYSDATE());



-- -----------------------------------------------------
-- Table `bds_consola_universal`.`ctAddresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bds_consola_universal`.`ctAddresses` ;

CREATE TABLE IF NOT EXISTS `bds_consola_universal`.`ctAddresses` (
  `IdAddress` INT(11) NOT NULL AUTO_INCREMENT,
  `IdCompany` INT(11) NOT NULL,
  `PhoneNum1` VARCHAR(20) NOT NULL,
  `PhoneNum2` VARCHAR(20) NOT NULL,
  `FaxNum` VARCHAR(20) NOT NULL,
  `Street` VARCHAR(250) NOT NULL,
  `InteriorNum` VARCHAR(10) NULL,
  `ExteriorNum` VARCHAR(10) NOT NULL,
  `Neighborhood` VARCHAR(250) NULL,
  `City` VARCHAR(250) NOT NULL,
  `State` VARCHAR(250) NOT NULL,
  `ZipCode` VARCHAR(10) NOT NULL,
  `IdCountry` INT(11) NOT NULL,
  `Created_Datetime` DATETIME NOT NULL,
  `Created_Platform` VARCHAR(10) NOT NULL,
  `Updated_Datetime` DATETIME NULL,
  `Updated_Platform` VARCHAR(10) NULL,
  PRIMARY KEY (`IdAddress`),
  CONSTRAINT `FK_Company_Country`
    FOREIGN KEY (`IdCountry`)
    REFERENCES `bds_consola_universal`.`ctCountries` (`IdCountry`)
  )
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `bds_consola_universal`.`cfProjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bds_consola_universal`.`ctProjects` ;

CREATE TABLE IF NOT EXISTS `bds_consola_universal`.`ctProjects` (
  `IdProject` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(50) NOT NULL,
  `Description` VARCHAR(250) NULL DEFAULT NULL,
  `IconUrl` VARCHAR(250) NULL DEFAULT NULL,
  `BadgeUrl` VARCHAR(250) NULL DEFAULT NULL,
  `Created_Datetime` DATETIME NOT NULL,
  `Created_Platform` VARCHAR(10) NOT NULL,
  `Updated_Datetime` DATETIME NULL DEFAULT NULL,
  `Updated_Platform` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`IdProject`)
  )
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;

INSERT INTO `bds_consola_universal`.`ctProjects` (`Name`, `Description`, `IconUrl`, `BadgeUrl`, `Created_Platform`, `Created_Datetime`) VALUES ('ConfGen', 'Generate and manage the configuration of your apps.', null, null, 'INIT_ROW', SYSDATE());

-- -----------------------------------------------------
-- Table `bds_consola_universal`.`rrUsersProjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bds_consola_universal`.`rrUsersProjects` ;

CREATE TABLE IF NOT EXISTS `bds_consola_universal`.`rrUsersProjects` (
  `IdUserProject` INT(11) NOT NULL AUTO_INCREMENT,
  `IdProject` INT(11) NOT NULL ,
  `IdUser` INT(11) NOT NULL ,
  `Unavaibled` CHAR(1) NOT NULL,
  `Datestart` DATETIME NOT NULL,
  `Datefinish` DATETIME NOT NULL,
  PRIMARY KEY (`IdUserProject`),
  CONSTRAINT `FK_UsersProjects_ctUsers`
    FOREIGN KEY (`IdUser`)
    REFERENCES `bds_consola_universal`.`ctUsers` (`IdUser`),
  CONSTRAINT `FK_rUsersProjects_ctProjects`
    FOREIGN KEY (`IdProject`)
    REFERENCES `bds_consola_universal`.`ctProjects` (`IdProject`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;

INSERT INTO `bds_consola_universal`.`rrUsersProjects` (`IdProject`, `IdUser`, `Unavaibled`, `Datestart`, `Datefinish`) VALUES  (1, 1, 'N', SYSDATE(), DATE_ADD(SYSDATE(), INTERVAL 1 YEAR));

-- -----------------------------------------------------
-- Table `bds_consola_universal`.`subscritionsOffers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bds_consola_universal`.`subscritionsOffers` ;

CREATE TABLE IF NOT EXISTS `bds_consola_universal`.`subscritionsOffers` (
  `IdOffer` INT(11) NOT NULL AUTO_INCREMENT,
  `IdProject` INT(11) NOT NULL ,
  `Description` VARCHAR(250) NOT NULL,
  `MaximumDownloads` INT NOT NULL,
  `MaximumUsers` TINYINT NOT NULL,
  `MaximumApplications` TINYINT NOT NULL,
  `MaximumProfiles` TINYINT NOT NULL,
  `MaximumVersionByApp` TINYINT NOT NULL,
  `Unavaibled` CHAR(1) NOT NULL,
  `Show` CHAR(1) NOT NULL,
  `Datestart` DATETIME NOT NULL,
  `Datefinish` DATETIME NOT NULL,
  `Created_Datetime` DATETIME NOT NULL,
  `Created_Platform` VARCHAR(10) NOT NULL,
  `Updated_Datetime` DATETIME NULL DEFAULT NULL,
  `Updated_Platform` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`IdOffer`),
  CONSTRAINT `FK_Offers_ctProjects`
    FOREIGN KEY (`IdProject`)
    REFERENCES `bds_consola_universal`.`ctProjects` (`IdProject`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;

INSERT INTO subscritionsOffers (`IdProject`, `Description`, `MaximumDownloads`, `MaximumUsers`, `MaximumApplications`, `MaximumProfiles`, `MaximumVersionByApp`, `Unavaibled`, `Show`, `Datestart`, `Datefinish`, `Created_Datetime`, `Created_Platform`, `Updated_Datetime`, `Updated_Platform`) 
VALUES (1, 'Config Generator is the most powerful tool in this moment to create and release the app configuration, by country, profile and version.', 1000000, 3, 1, 2, 10, 'F', 'Y', SYSDATE(), DATE_ADD(SYSDATE(), INTERVAL 1 YEAR), SYSDATE(), 'INIT_ROW', NULL, NULL);


-- -----------------------------------------------------
-- Table `bds_consola_universal`.`subscritionsOffers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bds_consola_universal`.`subscritionsSubscriptions` ;

CREATE TABLE IF NOT EXISTS `bds_consola_universal`.`subscritionsSubscriptions` (
  `IdSubscription` INT(11) NOT NULL AUTO_INCREMENT,
  `IdOffer` INT(11) NOT NULL,
  `IdBuyer` INT(11) NOT NULL,
  `Description` VARCHAR(250) NOT NULL,
  `MaximumDownloads` INT NOT NULL,
  `MaximumUsers` TINYINT NOT NULL,
  `MaximumApplications` TINYINT NOT NULL,
  `MaximumProfiles` TINYINT NOT NULL,
  `MaximumVersionByApp` TINYINT NOT NULL,
  `Unavaibled` CHAR(1) NOT NULL,
  `Show` CHAR(1) NOT NULL,
  `Datestart` DATETIME NOT NULL,
  `Datefinish` DATETIME NOT NULL,
  `Created_Datetime` DATETIME NOT NULL,
  `Created_Platform` VARCHAR(10) NOT NULL,
  `Updated_Datetime` DATETIME NULL DEFAULT NULL,
  `Updated_Platform` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`IdSubscription`),
  CONSTRAINT `FK_Subscriptions_Offers`
    FOREIGN KEY (`IdOffer`)
    REFERENCES `bds_consola_universal`.`subscritionsOffers` (`IdOffer`),
  CONSTRAINT `FK_Buyer`
    FOREIGN KEY (`IdBuyer`)
    REFERENCES `bds_consola_universal`.`ctUsers` (`IdUser`)
    )
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bds_consola_universal`.`rrOfferUsers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bds_consola_universal`.`rrSubscUsers` ;

CREATE TABLE IF NOT EXISTS `bds_consola_universal`.`rrSubscUsers` (
  `IdSubscUser` INT(11) NOT NULL AUTO_INCREMENT,
  `IdSubscription` INT(11) NOT NULL ,
  `IdUser` INT(11) NOT NULL,
  `Organizer` CHAR(1) NOT NULL,
  `Unavaibled` CHAR(1) NOT NULL,
  `Datestart` DATETIME NOT NULL,
  `Datefinish` DATETIME NOT NULL,
  PRIMARY KEY (`IdSubscUser`),
  CONSTRAINT `FK_SubsUsers_Subscriptions`
    FOREIGN KEY (`IdSubscription`)
    REFERENCES `bds_consola_universal`.`subscritionsSubscriptions` (`IdSubscription`),
  CONSTRAINT `FK_Subscription_Users`
    FOREIGN KEY (`IdUser`)
    REFERENCES `bds_consola_universal`.`ctUsers` (`IdUser`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;




-- -----------------------------------------------------
-- Table `bds_consola_universal`.`confgenApplications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bds_consola_universal`.`confgenApplications` ;

CREATE TABLE IF NOT EXISTS `bds_consola_universal`.`confgenApplications` (
  `IdApplication` INT(11) NOT NULL AUTO_INCREMENT,
  `IdSubscription` INT(11) NOT NULL ,
  `Name` VARCHAR(50) NOT NULL,
  `Show` CHAR(1) NOT NULL,
  `Unavaibled` CHAR(1) NOT NULL,
  PRIMARY KEY (`IdApplication`),
  UNIQUE INDEX `IdApplication` (`IdApplication` ASC),
  UNIQUE INDEX `Name` (`Name` ASC),
  CONSTRAINT `FK_Apps_Subscription`
    FOREIGN KEY (`IdSubscription`)
    REFERENCES `bds_consola_universal`.`subscritionsSubscriptions` (`IdSubscription`)
  )
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `bds_consola_universal`.`confgenVersions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bds_consola_universal`.`confgenVersions` ;

CREATE TABLE IF NOT EXISTS `bds_consola_universal`.`confgenVersions` (
  `IdVersion` INT(11) NOT NULL AUTO_INCREMENT,
  `IdApplication` INT(11) NOT NULL,
  `Name` VARCHAR(50) NOT NULL,
  `Show` CHAR(1) NOT NULL,
  `Unavaibled` CHAR(1) NOT NULL,
  PRIMARY KEY (`IdVersion`),
  UNIQUE INDEX `IdVersion` (`IdVersion` ASC),
  UNIQUE INDEX `Name` (`Name` ASC),
  INDEX `IdApplication` (`IdApplication` ASC),
  CONSTRAINT `FK_Versions_Applications`
    FOREIGN KEY (`IdApplication`)
    REFERENCES `bds_consola_universal`.`confgenApplications` (`IdApplication`))
ENGINE = InnoDB
AUTO_INCREMENT = 49
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;



-- -----------------------------------------------------
-- Table `bds_consola_universal`.`confgenProfile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bds_consola_universal`.`confgenProfiles` ;

CREATE TABLE IF NOT EXISTS `bds_consola_universal`.`confgenProfiles` (
  `IdProfile` INT(11) NOT NULL AUTO_INCREMENT,
  `IdSubscription` INT(11) NOT NULL ,
  `IdCountry` INT(11) NOT NULL,
  `Nombre` VARCHAR(50) NOT NULL,
  `Unavaibled` CHAR(1) NOT NULL,
  PRIMARY KEY (`IdProfile`),
  INDEX `idPais` (`IdCountry` ASC),
  CONSTRAINT `FK_Profiles_Countries`
    FOREIGN KEY (`idCountry`)
    REFERENCES `bds_consola_universal`.`ctCountries` (`IdCountry`),
  CONSTRAINT `FK_Porfile_Subscription`
    FOREIGN KEY (`IdSubscription`)
    REFERENCES `bds_consola_universal`.`subscritionsSubscriptions` (`IdSubscription`)
)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

-- -----------------------------------------------------
-- Table `bds_consola_universal`.`confgenVersionsByProfile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bds_consola_universal`.`confgenVersionsByProfile` ;

CREATE TABLE IF NOT EXISTS `bds_consola_universal`.`confgenVersionsByProfile` (
  `IdRelAppCountry` INT(11) NOT NULL AUTO_INCREMENT,
  `IdProfile` INT(11) NOT NULL,
  `IdVersion` INT(11) NOT NULL,
  PRIMARY KEY (`IdRelAppCountry`),
  INDEX `IdVersion` (`IdVersion` ASC),
  INDEX `IdProfile` (`IdProfile` ASC),
  CONSTRAINT `FK_rrAplicacionVer_ctVersiones`
    FOREIGN KEY (`IdVersion`)
    REFERENCES `bds_consola_universal`.`confgenVersions` (`IdVersion`),
  CONSTRAINT `FK_VersionsByProfile_Profiles`
    FOREIGN KEY (`IdProfile`)
    REFERENCES `bds_consola_universal`.`confgenProfiles` (`IdProfile`))
ENGINE = InnoDB
AUTO_INCREMENT = 253
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

-- -----------------------------------------------------
-- Table `bds_consola_universal`.`confgenConfigurations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bds_consola_universal`.`confgenConfigurations` ;

CREATE TABLE IF NOT EXISTS `bds_consola_universal`.`confgenConfigurations` (
  `IdConfiguracion` INT(11) NOT NULL AUTO_INCREMENT,
  `IdRelAppCountry` INT(11) NOT NULL,
  `Unavaibled` CHAR(1) NOT NULL,
  `Show` CHAR(1) NOT NULL,
  `Configuration` JSON NOT NULL,
  `Created_Datetime` DATETIME NOT NULL,
  `Created_Platform` VARCHAR(10) NOT NULL,
  `Updated_Datetime` DATETIME NULL,
  `Updated_Platform` VARCHAR(10) NULL,
  PRIMARY KEY (`IdConfiguracion`),
  INDEX `IdRelAppCountry` (`IdRelAppCountry` ASC),
  CONSTRAINT `FK_Configurations_VersionsByProfile`
    FOREIGN KEY (`IdRelAppCountry`)
    REFERENCES `bds_consola_universal`.`confgenVersionsByProfile` (`IdRelAppCountry`))
ENGINE = InnoDB
AUTO_INCREMENT = 19198
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

-- -----------------------------------------------------
-- Table `bds_consola_universal`.`confgenConfigurationChanges`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bds_consola_universal`.`confgenConfigurationChanges` ;

CREATE TABLE IF NOT EXISTS `bds_consola_universal`.`confgenConfigurationChanges` (
  `IdIConfiguracionChange` INT(11) NOT NULL AUTO_INCREMENT,
  `IdConfiguracion` INT(11) NOT NULL,
  `Configuration` JSON NOT NULL,
  `Created_Datetime` DATETIME NOT NULL,
  `Created_Platform` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`IdIConfiguracionChange`),
  CONSTRAINT `FK_Config_Changes`
    FOREIGN KEY (`IdConfiguracion`)
    REFERENCES `bds_consola_universal`.`confgenConfigurations` (`IdConfiguracion`))
ENGINE = InnoDB
AUTO_INCREMENT = 19198
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- ***************************************************************************************************************************************************************************************
-- ***************************************************************************************************************************************************************************************
/*



-- -----------------------------------------------------
-- Table `bds_consola_universal`.`ctCambios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bds_consola_universal`.`ctCambios` ;

CREATE TABLE IF NOT EXISTS `bds_consola_universal`.`ctCambios` (
  `idCambio` INT(11) NOT NULL,
  `IdRelAppPais_base` INT(11) NOT NULL,
  `fecha_hora` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idCambio`, `IdRelAppPais_base`),
  INDEX `IdRelAppPais_cambios_idx` (`IdRelAppPais_base` ASC),
  CONSTRAINT `IdRelAppPais_base_fk`
    FOREIGN KEY (`IdRelAppPais_base`)
    REFERENCES `bds_consola_universal`.`rrAplicacionVersionPais` (`IdRelAppPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'tabla que almacenará un consecutivo de cambio por cada versión asi como la fecha-hora en que se agrega el registro';


-- ***************************************************************************************************************************************************************************************
-- ***************************************************************************************************************************************************************************************
-- -----------------------------------------------------
-- Table `bds_consola_universal`.`ctUsuarioAreas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bds_consola_universal`.`ctUsuarioAreas` ;

CREATE TABLE IF NOT EXISTS `bds_consola_universal`.`ctUsuarioAreas` (
  `IdUsuarioArea` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Notifica` CHAR(1) NOT NULL,
  PRIMARY KEY (`IdUsuarioArea`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

INSERT INTO `bds_consola_universal`.`ctUsuarioAreas` (`Nombre`, `Notifica`) VALUES ('Infraestructura', 'Y');
INSERT INTO `bds_consola_universal`.`ctUsuarioAreas` (`Nombre`, `Notifica`) VALUES ('Negocio', 'Y');
INSERT INTO `bds_consola_universal`.`ctUsuarioAreas` (`Nombre`, `Notifica`) VALUES ('Desarrollo BE', 'Y');
INSERT INTO `bds_consola_universal`.`ctUsuarioAreas` (`Nombre`, `Notifica`) VALUES ('Desarrollo Apps', 'Y');
INSERT INTO `bds_consola_universal`.`ctUsuarioAreas` (`Nombre`, `Notifica`) VALUES ('QA', 'Y');
INSERT INTO `bds_consola_universal`.`ctUsuarioAreas` (`Nombre`, `Notifica`) VALUES ('Soporte', 'Y');
INSERT INTO `bds_consola_universal`.`ctUsuarioAreas` (`Nombre`, `Notifica`) VALUES ('Líder', 'Y');


-- -----------------------------------------------------
-- Table `bds_consola_universal`.`ctUsuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bds_consola_universal`.`ctUsuarios` ;

CREATE TABLE IF NOT EXISTS `bds_consola_universal`.`ctUsuarios` (
  `IdUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `IdUsuarioArea` INT(11) NOT NULL,
  `Contrasena` VARCHAR(150) NOT NULL,
  `Eliminar` CHAR(1) NOT NULL,
  `Nombre` VARCHAR(50) NOT NULL,
  `Email` VARCHAR(150) NOT NULL,
  `Superusuario` CHAR(1) NOT NULL,
  PRIMARY KEY (`IdUsuario`),
  CONSTRAINT `FK_Usuario_Area`
    FOREIGN KEY (`IdUsuarioArea`)
    REFERENCES `bds_consola_universal`.`ctUsuarioAreas` (`IdUsuarioArea`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

INSERT INTO `bds_consola_universal`.`ctUsuarios` (`IdUsuarioArea`, `Contrasena`, `Eliminar`, `Nombre`, `Email`, `Superusuario`) VALUES (1, 'admin', 'N', 'Alfredo Barrios', 'alfredo.barrios@speedymovil.com', 'Y');
INSERT INTO `bds_consola_universal`.`ctUsuarios` (`IdUsuarioArea`, `Contrasena`, `Eliminar`, `Nombre`, `Email`, `Superusuario`) VALUES (1, 'chicharron', 'N', 'Javier Hernández', 'javier.hernandez@speedymovil.com', 'Y');
INSERT INTO `bds_consola_universal`.`ctUsuarios` (`IdUsuarioArea`, `Contrasena`, `Eliminar`, `Nombre`, `Email`, `Superusuario`) VALUES (2, '12345', 'N', 'Ana Karen Suárez', 'ana.suarez@speedymovil.com', 'Y');
INSERT INTO `bds_consola_universal`.`ctUsuarios` (`IdUsuarioArea`, `Contrasena`, `Eliminar`, `Nombre`, `Email`, `Superusuario`) VALUES (3, '12345', 'N', 'Magdalena Rodríguez', 'magdalena.rodriguez@speedymovil.com', 'Y');
INSERT INTO `bds_consola_universal`.`ctUsuarios` (`IdUsuarioArea`, `Contrasena`, `Eliminar`, `Nombre`, `Email`, `Superusuario`) VALUES (4, '12345', 'N', 'Luis Regalado', 'luis.regalado@speedymovil.com', 'Y');
INSERT INTO `bds_consola_universal`.`ctUsuarios` (`IdUsuarioArea`, `Contrasena`, `Eliminar`, `Nombre`, `Email`, `Superusuario`) VALUES (5, '12345', 'N', 'Karen López', 'qasupervision@speedymovil.com', 'Y');
INSERT INTO `bds_consola_universal`.`ctUsuarios` (`IdUsuarioArea`, `Contrasena`, `Eliminar`, `Nombre`, `Email`, `Superusuario`) VALUES (6, '12345', 'N', 'Soporte', 'soporte@speedymovil.com', 'Y');
INSERT INTO `bds_consola_universal`.`ctUsuarios` (`IdUsuarioArea`, `Contrasena`, `Eliminar`, `Nombre`, `Email`, `Superusuario`) VALUES (7, '12345', 'N', 'Diego Mota', 'diego.mota@speedymovil.com', 'Y');

-- -----------------------------------------------------
-- Table `bds_consola_universal`.`rpBitacora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bds_consola_universal`.`rpBitacora` ;

CREATE TABLE IF NOT EXISTS `bds_consola_universal`.`rpBitacora` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Evento` INT(11) NOT NULL,
  `Fechahora` DATE NOT NULL,
  `Aplicacion` VARCHAR(50) NOT NULL,
  `Version` VARCHAR(50) NOT NULL,
  `Pais` VARCHAR(50) NOT NULL,
  `Perfil` VARCHAR(50) NOT NULL,
  `NuevoCambio` CHAR(1) NOT NULL,
  `VersionVersion` VARCHAR(50) NOT NULL,
  `Usuario` VARCHAR(50) NOT NULL,
  `Nodo` VARCHAR(2500) NOT NULL,
  `Requerimiento` VARCHAR(2500) NOT NULL,
  `Release` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;
-- ***************************************************************************************************************************************************************************************
-- ***************************************************************************************************************************************************************************************

-- -----------------------------------------------------
-- Table `bds_consola_universal`.`dtConfigValores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bds_consola_universal`.`dtConfigValores` ;

CREATE TABLE IF NOT EXISTS `bds_consola_universal`.`dtConfigValores` (
  `IdConfigValor` INT(11) NOT NULL AUTO_INCREMENT,
  `IdItemConfiguracion` INT(11) NOT NULL,
  `Atributo` VARCHAR(50) NOT NULL,
  `Valor` VARCHAR(2500) NULL DEFAULT NULL,
  `Mostrar` CHAR(1) NOT NULL,
  `SiempreEsArreglo` CHAR(1) NOT NULL,
  PRIMARY KEY (`IdConfigValor`),
  INDEX `IdItemConfiguracion` (`IdItemConfiguracion` ASC),
  CONSTRAINT `FK_dtConfigValor_ftItemsConfig`
    FOREIGN KEY (`IdItemConfiguracion`)
    REFERENCES `bds_consola_universal`.`ftItemsConfiguracion` (`IdItemConfiguracion`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 76091
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `bds_consola_universal`.`rrAppPaisVSUsuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bds_consola_universal`.`rrAppPaisVSUsuarios` ;

CREATE TABLE IF NOT EXISTS `bds_consola_universal`.`rrAppPaisVSUsuarios` (
  `IdAppPaisVSUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `IdRelAppPais` INT(11) NOT NULL,
  `IdUsuario` INT(11) NOT NULL,
  PRIMARY KEY (`IdAppPaisVSUsuario`),
  INDEX `IdRelAppPais` (`IdRelAppPais` ASC),
  INDEX `IdUsuario` (`IdUsuario` ASC),
  CONSTRAINT `FK_rrAppPaisVSUs_rrAplicacionP`
    FOREIGN KEY (`IdRelAppPais`)
    REFERENCES `bds_consola_universal`.`rrAplicacionVersionPais` (`IdRelAppPais`),
  CONSTRAINT `FK_rrAppPaisVSUsuar_ctUsuarios`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `bds_consola_universal`.`ctUsuarios` (`IdUsuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 265
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `bds_consola_universal`.`rrListaItems`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bds_consola_universal`.`rrListaItems` ;

CREATE TABLE IF NOT EXISTS `bds_consola_universal`.`rrListaItems` (
  `IdItem` INT(11) NOT NULL AUTO_INCREMENT,
  `IdConfigValor` INT(11) NOT NULL,
  `IdItemConfiguracion` INT(11) NOT NULL,
  PRIMARY KEY (`IdItem`),
  UNIQUE INDEX `IdItem` (`IdItem` ASC),
  INDEX `IdItemConfiguracion` (`IdItemConfiguracion` ASC),
  INDEX `IdConfigValor` (`IdConfigValor` ASC),
  CONSTRAINT `FK_ListaItems_dtConfigValores`
    FOREIGN KEY (`IdConfigValor`)
    REFERENCES `bds_consola_universal`.`dtConfigValores` (`IdConfigValor`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_Lista_VS_Items`
    FOREIGN KEY (`IdItemConfiguracion`)
    REFERENCES `bds_consola_universal`.`ftItemsConfiguracion` (`IdItemConfiguracion`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 14935
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;
*/

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


DROP PROCEDURE IF EXISTS `bds_consola_universal`.`REGISTER`;
DELIMITER $$
CREATE PROCEDURE `bds_consola_universal`.`REGISTER` (
in p_platform VARCHAR(10), 
in p_name VARCHAR(50), 
in p_lastname VARCHAR(50), 
in p_organization VARCHAR(250), 
in p_area VARCHAR(50), 
in p_email VARCHAR(150), 
in p_password VARCHAR(100),
in p_photo VARCHAR(200))
BEGIN
-- *************************************************************************************************************************
-- * CREATE_USER
-- *************************************************************************************************************************
-- * This procedures adds a new user
-- * Create by: Alfredo Barrios
-- * Created at: Jun 11, 2020
-- *************************************************************************************************************************
	DECLARE v_IdUser INT;
	DECLARE v_IdUserArea INT;
	DECLARE v_IdOrganization INT;
	DECLARE v_IdOrganizationAdded INT unsigned DEFAULT 0;
	-- Handler error
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;  -- rollback any error in the transaction
    END;
    IF (SELECT COUNT(*) FROM `bds_consola_universal`.`ctUsers` WHERE p_email=`email`) > 0 THEN
    BEGIN
		SIGNAL sqlstate '45000'
        SET MESSAGE_TEXT = 'EMAIL_ALREADY_EXISTS';
	END;
    END IF;
	START TRANSACTION;
		IF (SELECT COUNT(*) FROM `bds_consola_universal`.`ctUserAreas` WHERE p_area=`name`) = 0 THEN
			INSERT INTO `bds_consola_universal`.`ctUserAreas` (`name`, `Notify`) VALUES (p_area, 'N');
		END IF;    
		SELECT `IdUserArea` into v_IdUserArea FROM `bds_consola_universal`.`ctUserAreas` WHERE p_area=`name`;
		-- ********************************************************************************************************************
		IF (SELECT COUNT(*) FROM `bds_consola_universal`.`ctOrganizations` WHERE p_organization=`name`) = 0 THEN
			INSERT INTO `bds_consola_universal`.`ctOrganizations` (`Name`, `IdUserOnCharge`, `Created_Platform`, `Created_Datetime`) VALUES (p_organization, 1, p_platform, SYSDATE());
			SET v_IdOrganizationAdded = 1;
		END IF;
		SELECT `IdOrganization` into v_IdOrganization FROM `bds_consola_universal`.`ctOrganizations` WHERE p_organization=`name`;
		INSERT INTO `bds_consola_universal`.`ctUsers` (`IdUserArea`, `Password`, `Unavaibled`, `Name`, `Lastname`, `Email`, `Superuser`, `Confirmed`, `IdOrganization`, `photo`, `Created_Platform`, `Created_Datetime`) VALUES 
		(v_IdUserArea, p_password, 'N', p_name, p_lastname, p_email, 'N', 'N', v_IdOrganization, p_photo, p_platform, SYSDATE());
		SELECT `IdUser` into v_IdUser FROM `bds_consola_universal`.`ctUsers` WHERE p_email=`Email`;
		IF v_IdOrganizationAdded=1 THEN
			UPDATE `bds_consola_universal`.`ctOrganizations` SET `IdUserOnCharge`= v_IdUser WHERE v_IdOrganization=`IdOrganization`;
		END IF;
    COMMIT;
    SELECT usr.`IdUser`
    , usr.`IdUserArea`
    , usra.`name` AS `UserArea`
    , usr.`IdOrganization`
    , orgn.`name` AS `Organization`
    , usr.`IdOrganizationRol`
    , orgr.`nameES` AS `OrganizationRol`
    , usr.`Password`
    , usr.`Name`
    , usr.`Lastname`
    , usr.`Email`
    , usr.`Superuser`
    , usr.`Confirmed`
    , usr.`Photo`
    , usr.`Unavaibled`
    , usr.`Created_Datetime`
    , usr.`Created_Platform`
    , usr.`Updated_Datetime`
    , usr.`Updated_Platform` 
    FROM `bds_consola_universal`.`ctUsers` usr INNER JOIN `bds_consola_universal`.`ctUserAreas` usra ON usr.`IdUserArea`= usra.`IdUserArea`
    INNER JOIN `bds_consola_universal`.`ctOrganizations` orgn ON usr.`IdOrganization`= orgn.`IdOrganization`
    LEFT OUTER JOIN `bds_consola_universal`.`ctOrganizationRoles` orgr ON orgr.`IdOrganizationRol`=usr.`IdOrganizationRol`
    WHERE p_iduser=usr.iduser;
END
$$
DELIMITER ;
